nucleos_user:
    db_driver: orm # other valid values is 'mongodb'

    firewall_name: main

    from_email: '%env(MAIL_SENDER)%'

    user_class: 'App\Entity\Utilisateur'

#    group:
#        group_class: 'App\Entity\User\Group'
