# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
#  transport: gmail
#    username: myfitzonewebsite@gmail.com
#    password: Sportmfzmdp2021
#    host: localhost
#    port: 465
#    encryption: ssl
#    auth-mode: login
#    spool: { type: 'memory' }
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
